//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectosena.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class actualizacion
    {
        public int idactualizacion { get; set; }
        public Nullable<int> registroad { get; set; }
        public Nullable<int> registroem { get; set; }
    
        public virtual registroad registroad1 { get; set; }
        public virtual registroem registroem1 { get; set; }
    }
}
