//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectosena.modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class modelocmContainer : DbContext
    {
        public modelocmContainer()
            : base("name=modelocmContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actualizacion> actualizacion { get; set; }
        public virtual DbSet<loginadministrador> loginadministrador { get; set; }
        public virtual DbSet<loginempleado> loginempleado { get; set; }
        public virtual DbSet<registroad> registroad { get; set; }
        public virtual DbSet<registroem> registroem { get; set; }
        public virtual DbSet<reportes> reportes { get; set; }
        public virtual DbSet<test> test { get; set; }
    }
}
