//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectosena.modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public test()
        {
            this.reportes = new HashSet<reportes>();
        }
    
        public int idtestemple { get; set; }
        public string prg1 { get; set; }
        public string prg2 { get; set; }
        public string prg3 { get; set; }
        public string prg4 { get; set; }
        public string prg5 { get; set; }
        public string prg6 { get; set; }
        public string prg7 { get; set; }
        public string prg8 { get; set; }
        public Nullable<int> registroem { get; set; }
    
        public virtual registroem registroem1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reportes> reportes { get; set; }
    }
}
