//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectosena.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cmhumanEntities : DbContext
    {
        public cmhumanEntities()
            : base("name=cmhumanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<datoemple> datoemple { get; set; }
        public virtual DbSet<loginadministrador> loginadministrador { get; set; }
        public virtual DbSet<loginempleado> loginempleado { get; set; }
        public virtual DbSet<test> test { get; set; }
    }
}
