//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectosena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int idtestemple { get; set; }
        public string prg1 { get; set; }
        public string prg2 { get; set; }
        public string prg3 { get; set; }
        public string prg4 { get; set; }
        public string prg5 { get; set; }
        public string prg6 { get; set; }
        public string prg7 { get; set; }
        public string prg8 { get; set; }
        public Nullable<int> idci { get; set; }
    
        public virtual datoemple datoemple { get; set; }
    }
}
